/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RecipApp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        Ingredient classUnderTest = new Ingredient("null", "null", 0);
        assertNotNull("app adds Ingredients", classUnderTest.getName());
    }
}
